export const colors = {
  PRIMARY_COLOR: '#000000',
  SECONDARY_COLOR: '#a4acad',
  MAIN_ACCENT_COLOR: '#ff9846',
  ACTIVE_ACCENT_COLOR: '#f46d40',
  MAIN_LIGHT_COLOR: '#fff',
  MAIN_DARK_COLOR: '#111111',
  AUXILIARY_LIGHT_COLOR: '#f2f2f2',
};
